apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: storage-agent-lvmd
  namespace: zcloud
  labels:
    app: storage-agent-lvmd
spec:
  selector:
    matchLabels:
      app: storage-agent-lvmd
  template:
    metadata:
      labels:
        app: storage-agent-lvmd
    spec:
      hostNetwork: true
      nodeSelector: 
        storage.zcloud.cn/storagetype: Lvm
      containers:
      - name: storage-agent-lvmd
        image: zdnscloud/lvmd:v0.92
        command: ["/bin/sh", "-c", "/lvmd", "-listen", "0.0.0.0:1736"]
        env:
          - name: NodeName
            valueFrom:
              fieldRef: 
                fieldPath: spec.nodeName
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
          allowPrivilegeEscalation: true
        volumeMounts:
          - mountPath: /dev
            name: host-dev
      volumes:
        - name: host-dev
          hostPath:
            path: /dev
