apiVersion: storage.zcloud.cn/v1
kind: Cluster
metadata:
  name: lvm-cluster
spec:
  storageType: "lvm"
  hosts: 
  - nodeName: "k8s-02"
    blockDevices: ["/dev/vdb"]
  - nodeName: "k8s-03"
    blockDevices: ["/dev/vdb"]
